Update ActiveFedora gem + fix backword compability
Updated ActiveFedora gem from 9.7.0 to 10.3.0. Note this component only works with Fedor 4.6.1+

This change breaks the backword code compability. Quick fix has been introduced in Register and Folio models where 'contains' relationship has been removed (See commented code).

*Apendix*
Dependency erro

  ```NoMethodError: undefined method `contains' for Register:Class ```

shows when http://127.0.0.1:3000/iiif/manifest/7m01bn44b call is executed.

Same error seen in Folio model.